
apiVersion: v1
kind: Service
metadata:
  name: ldvy-ws-service-production
spec:
  type: NodePort
  selector:
    app: ldvy-ws
  ports:
  - protocol: TCP
    port: 80
    nodetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldvy-ws-deployment-production
  labels:
    app: ldvy-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ldvy-ws
  template:
    metadata:
      labels:
        app: ldvy-ws
    spec:
      nodeSelector:
        type: production
      containers:
      - name: ldvy-ws
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80

