
apiVersion: v1
kind: Service
metadata:
  name: ldvy-ws-service
spec:
  type: NodePort
  selector:
    app: ldvy-ws
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30036

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldvy-ws-deployment
  labels:
    app: ldvy-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ldvy-ws
  template:
    metadata:
      labels:
        app: ldvy-ws
    spec:
      containers:
      - name: ldvy-ws
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
